name: Migrate Garmin Global to Garmin CN

on:
  workflow_dispatch:

env:
  BARK_KEY: ${{ secrets.BARK_KEY }}
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME_DEFAULT }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD_DEFAULT }}
  GARMIN_GLOBAL_USERNAME: ${{ secrets.GARMIN_USERNAME_DEFAULT }}
  GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_PASSWORD_DEFAULT }}
  GARMIN_MIGRATE_NUM: 100
  GARMIN_MIGRATE_START: 100

jobs:
  build:
    runs-on: ubuntu-latest
    name: Migrate Garmin Global to Garmin CN
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn
      - run: yarn migrate_garmin_global_to_cn
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Save Garmin Session
